### ISSUE TITLE
hi, can add text similarity, percentage?

### ISSUE THREAD

**Issue by jiangyimm** [thezaza101/textdiffcore#3]

**Comment by thezaza101** [comment]
I don't think this package would be suitable for calculating that; you can use the Levenshtein distance algorithm then divide that by the total number of words.. see: https://stackoverflow.com/questions/6087281/similarity-score-levenshtein

If you want to calculate the % of different words, you can use this package by counting the number of elements returned from  ```GenerateDiffOutput``` and then dividing that by the number of words (similar concept to above).
